# Generated by Django 4.2 on 2025-04-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20, unique=True)),
                ('car_type', models.CharField(max_length=20)),
                ('incoming_time', models.DateTimeField(auto_now_add=True)),
                ('outgoing_time', models.DateTimeField(blank=True, null=True)),
                ('parking_slot', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
